### ISSUE TITLE
Améliorer le wiki

### ISSUE THREAD

**Issue by moussadiallo** [dioula97/Eureka#1]
Interessant.
Améliorer le wiki en fournissant de la docementation.

**Comment by dioula97** [comment]
Ok pas de souci merci.

**Comment by dioula97** [comment]
Ok pouvez-vous me donner une brève explication de la structure d'une documentation


Sent from my Verizon, Samsung Galaxy smartphone
-------- Message d'origine --------De : moussa diallo <notifications@github.com> Date : 20/01/2018  15:09  (GMT+00:00) À : dioula97/L-Etudiant <L-Etudiant@noreply.github.com> Cc : dioula97 <balboucka@gmail.com>, Assign <assign@noreply.github.com> Objet : [dioula97/L-Etudiant] Améliorer le wiki (#1) 
Interessant.

Améliorer le wiki en fournissant de la docementation.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dioula97/L-Etudiant","title":"dioula97/L-Etudiant","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dioula97/L-Etudiant"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Améliorer le wiki (#1)"}],"action":{"name":"View Issue","url":"https://github.com/dioula97/L-Etudiant/issues/1"}}}

**Comment by moussadiallo** [comment]
Il faut faire une étude sur le terrain, rencontrer les gens à qui la platerforme est destinée, recueillir des témoignages et ensuite décrire comment l'application sera en te basant sur ces fits là.

**Comment by moussadiallo** [comment]
c'est bien

**Comment by dioula97** [comment]
Merci Monsieur

Provenance : Courrier pour Windows 10

De : moussa diallo
Envoyé le :dimanche 28 janvier 2018 13:10
À : dioula97/Eureka
Cc : dioula97; State change
Objet :Re: [dioula97/Eureka] Améliorer le wiki (#1)

c'est bien

**Comment by dioula97** [comment]
Hey,

I just signed the petition "Emmanuel Macron : Non à l'augmentation des
frais d'inscription pour les étudiant.e.s étranger.e.s !" and wanted to see
if you could help by adding your name.

Our goal is to reach 304 695 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/MYWNFLVyVD

Thanks!
Mairame
